# Form implementation generated from reading ui file '.\src\gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 595)
        MainWindow.setMinimumSize(QtCore.QSize(550, 595))
        MainWindow.setMaximumSize(QtCore.QSize(550, 595))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(2.0)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 0, 511, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.b_egale = QtWidgets.QPushButton(parent=self.centralwidget)
        self.b_egale.setGeometry(QtCore.QRect(430, 490, 100, 60))
        self.b_egale.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";color: rgb(85, 85, 255);\n"
"background-color: rgb(255, 255, 127);")
        self.b_egale.setObjectName("b_egale")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 280, 181, 31))
        self.label.setStyleSheet("color: rgb(0, 150, 255);\n"
"\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(255, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(19, 440, 77, 113))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_ans_1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_ans_1.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 90);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_ans_1.setObjectName("pushButton_ans_1")
        self.verticalLayout.addWidget(self.pushButton_ans_1)
        self.pushButton_ans_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_ans_2.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 90);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_ans_2.setObjectName("pushButton_ans_2")
        self.verticalLayout.addWidget(self.pushButton_ans_2)
        self.pushButton_ans_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_ans_3.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 90);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_ans_3.setObjectName("pushButton_ans_3")
        self.verticalLayout.addWidget(self.pushButton_ans_3)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 440, 321, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ans_1 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_ans_1.setStyleSheet("color: rgb(0, 150, 255);\n"
"\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(255, 0, 0);")
        self.label_ans_1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_ans_1.setLineWidth(2)
        self.label_ans_1.setText("")
        self.label_ans_1.setObjectName("label_ans_1")
        self.verticalLayout_2.addWidget(self.label_ans_1)
        self.label_ans_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_ans_2.setStyleSheet("color: rgb(0, 150, 255);\n"
"\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_ans_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_ans_2.setLineWidth(2)
        self.label_ans_2.setText("")
        self.label_ans_2.setObjectName("label_ans_2")
        self.verticalLayout_2.addWidget(self.label_ans_2)
        self.label_ans_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_ans_3.setStyleSheet("color: rgb(0, 150, 255);\n"
"\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_ans_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_ans_3.setLineWidth(2)
        self.label_ans_3.setText("")
        self.label_ans_3.setObjectName("label_ans_3")
        self.verticalLayout_2.addWidget(self.label_ans_3)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 320, 511, 113))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_c = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_c.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton_c.setObjectName("pushButton_c")
        self.gridLayout_3.addWidget(self.pushButton_c, 0, 0, 1, 1)
        self.pushButton_qe = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_qe.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_qe.setObjectName("pushButton_qe")
        self.gridLayout_3.addWidget(self.pushButton_qe, 0, 1, 1, 1)
        self.pushButton_me = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_me.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_me.setObjectName("pushButton_me")
        self.gridLayout_3.addWidget(self.pushButton_me, 0, 2, 1, 1)
        self.pushButton_a0 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_a0.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_a0.setObjectName("pushButton_a0")
        self.gridLayout_3.addWidget(self.pushButton_a0, 0, 3, 1, 1)
        self.pushButton_mu0 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_mu0.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_mu0.setObjectName("pushButton_mu0")
        self.gridLayout_3.addWidget(self.pushButton_mu0, 0, 4, 1, 1)
        self.pushButton_h = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_h.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_h.setObjectName("pushButton_h")
        self.gridLayout_3.addWidget(self.pushButton_h, 1, 0, 1, 1)
        self.pushButton_eV = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_eV.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_eV.setObjectName("pushButton_eV")
        self.gridLayout_3.addWidget(self.pushButton_eV, 1, 1, 1, 1)
        self.pushButton_mp = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_mp.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_mp.setObjectName("pushButton_mp")
        self.gridLayout_3.addWidget(self.pushButton_mp, 1, 2, 1, 1)
        self.pushButton_Rm = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_Rm.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_Rm.setObjectName("pushButton_Rm")
        self.gridLayout_3.addWidget(self.pushButton_Rm, 1, 3, 1, 1)
        self.pushButton_eps0 = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_eps0.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_eps0.setObjectName("pushButton_eps0")
        self.gridLayout_3.addWidget(self.pushButton_eps0, 1, 4, 1, 1)
        self.pushButton_hbar = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_hbar.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_hbar.setObjectName("pushButton_hbar")
        self.gridLayout_3.addWidget(self.pushButton_hbar, 2, 0, 1, 1)
        self.pushButton_kB = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_kB.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_kB.setObjectName("pushButton_kB")
        self.gridLayout_3.addWidget(self.pushButton_kB, 2, 1, 1, 1)
        self.pushButton_mn = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_mn.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_mn.setObjectName("pushButton_mn")
        self.gridLayout_3.addWidget(self.pushButton_mn, 2, 2, 1, 1)
        self.pushButton_Rinf = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_Rinf.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_Rinf.setObjectName("pushButton_Rinf")
        self.gridLayout_3.addWidget(self.pushButton_Rinf, 2, 3, 1, 1)
        self.pushButton_NA = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.pushButton_NA.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(0, 150, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_NA.setObjectName("pushButton_NA")
        self.gridLayout_3.addWidget(self.pushButton_NA, 2, 4, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 50, 171, 261))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_cos = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_cos.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.gridLayout.addWidget(self.pushButton_cos, 0, 0, 1, 1)
        self.pushButton_sin = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_sin.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.gridLayout.addWidget(self.pushButton_sin, 0, 1, 1, 1)
        self.pushButton_tan = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_tan.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.gridLayout.addWidget(self.pushButton_tan, 1, 0, 1, 1)
        self.pushButton_pow = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_pow.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_pow.setObjectName("pushButton_pow")
        self.gridLayout.addWidget(self.pushButton_pow, 1, 1, 1, 1)
        self.pushButton_log = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_log.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_log.setObjectName("pushButton_log")
        self.gridLayout.addWidget(self.pushButton_log, 2, 0, 1, 1)
        self.pushButton_ln = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_ln.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_ln.setObjectName("pushButton_ln")
        self.gridLayout.addWidget(self.pushButton_ln, 2, 1, 1, 1)
        self.pushButton_pow2 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_pow2.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_pow2.setObjectName("pushButton_pow2")
        self.gridLayout.addWidget(self.pushButton_pow2, 3, 0, 1, 1)
        self.pushButton_sqrt = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_sqrt.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_sqrt.setObjectName("pushButton_sqrt")
        self.gridLayout.addWidget(self.pushButton_sqrt, 3, 1, 1, 1)
        self.pushButton_pi = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_pi.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_pi.setObjectName("pushButton_pi")
        self.gridLayout.addWidget(self.pushButton_pi, 4, 0, 1, 1)
        self.pushButton_e = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_e.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_e.setObjectName("pushButton_e")
        self.gridLayout.addWidget(self.pushButton_e, 4, 1, 1, 1)
        self.pushButton_inv = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_inv.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_inv.setObjectName("pushButton_inv")
        self.gridLayout.addWidget(self.pushButton_inv, 5, 0, 1, 1)
        self.pushButton_factorial = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.pushButton_factorial.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.gridLayout.addWidget(self.pushButton_factorial, 5, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(430, 440, 100, 40))
        self.pushButton_clear.setStyleSheet("background-color: rgb(255, 39, 143);font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 50, 331, 231))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b_del = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_del.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_del.setObjectName("b_del")
        self.gridLayout_2.addWidget(self.b_del, 0, 0, 1, 1)
        self.b_po = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_po.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_po.setObjectName("b_po")
        self.gridLayout_2.addWidget(self.b_po, 0, 1, 1, 1)
        self.b_pf = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_pf.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_pf.setObjectName("b_pf")
        self.gridLayout_2.addWidget(self.b_pf, 0, 2, 1, 1)
        self.b_moins = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_moins.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_moins.setObjectName("b_moins")
        self.gridLayout_2.addWidget(self.b_moins, 0, 3, 1, 1)
        self.b_7 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_7.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_7.setObjectName("b_7")
        self.gridLayout_2.addWidget(self.b_7, 1, 0, 1, 1)
        self.b_8 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_8.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_8.setObjectName("b_8")
        self.gridLayout_2.addWidget(self.b_8, 1, 1, 1, 1)
        self.b_9 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_9.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_9.setObjectName("b_9")
        self.gridLayout_2.addWidget(self.b_9, 1, 2, 1, 1)
        self.b_plus = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_plus.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.b_plus.setObjectName("b_plus")
        self.gridLayout_2.addWidget(self.b_plus, 1, 3, 1, 1)
        self.b_4 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_4.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_4.setObjectName("b_4")
        self.gridLayout_2.addWidget(self.b_4, 2, 0, 1, 1)
        self.b_5 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_5.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_5.setObjectName("b_5")
        self.gridLayout_2.addWidget(self.b_5, 2, 1, 1, 1)
        self.b_6 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_6.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.b_6.setObjectName("b_6")
        self.gridLayout_2.addWidget(self.b_6, 2, 2, 1, 1)
        self.b_divise = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_divise.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_divise.setObjectName("b_divise")
        self.gridLayout_2.addWidget(self.b_divise, 2, 3, 1, 1)
        self.b_1 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_1.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.b_1.setObjectName("b_1")
        self.gridLayout_2.addWidget(self.b_1, 3, 0, 1, 1)
        self.b_2 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_2.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.b_2.setObjectName("b_2")
        self.gridLayout_2.addWidget(self.b_2, 3, 1, 1, 1)
        self.b_3 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_3.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.b_3.setObjectName("b_3")
        self.gridLayout_2.addWidget(self.b_3, 3, 2, 1, 1)
        self.b_mult = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_mult.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_mult.setObjectName("b_mult")
        self.gridLayout_2.addWidget(self.b_mult, 3, 3, 1, 1)
        self.b_0 = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_0.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";color: rgb(0, 170, 255);\n"
"color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.b_0.setObjectName("b_0")
        self.gridLayout_2.addWidget(self.b_0, 4, 0, 1, 1)
        self.b_point = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.b_point.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.b_point.setObjectName("b_point")
        self.gridLayout_2.addWidget(self.b_point, 4, 1, 1, 1)
        self.pushButton_pm = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.pushButton_pm.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(85, 255, 255);font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_pm.setObjectName("pushButton_pm")
        self.gridLayout_2.addWidget(self.pushButton_pm, 4, 2, 1, 1)
        self.pushButton_E = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.pushButton_E.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_E.setObjectName("pushButton_E")
        self.gridLayout_2.addWidget(self.pushButton_E, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_clear.clicked.connect(self.lineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhysiCalc (by aymen mahmoudi)"))
        self.b_egale.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "Physcial constant"))
        self.pushButton_ans_1.setText(_translate("MainWindow", "ANS"))
        self.pushButton_ans_2.setText(_translate("MainWindow", "ANS"))
        self.pushButton_ans_3.setText(_translate("MainWindow", "ANS"))
        self.pushButton_c.setText(_translate("MainWindow", "c"))
        self.pushButton_qe.setText(_translate("MainWindow", "qₑ"))
        self.pushButton_me.setText(_translate("MainWindow", "mₑ"))
        self.pushButton_a0.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>mpp</p></body></html>"))
        self.pushButton_a0.setText(_translate("MainWindow", "a₀"))
        self.pushButton_mu0.setText(_translate("MainWindow", "μ₀"))
        self.pushButton_h.setText(_translate("MainWindow", "h"))
        self.pushButton_eV.setText(_translate("MainWindow", "eV"))
        self.pushButton_mp.setText(_translate("MainWindow", "mₚ"))
        self.pushButton_Rm.setText(_translate("MainWindow", "Rm"))
        self.pushButton_eps0.setText(_translate("MainWindow", "ε₀"))
        self.pushButton_hbar.setText(_translate("MainWindow", "ℏ"))
        self.pushButton_kB.setText(_translate("MainWindow", "kB"))
        self.pushButton_mn.setText(_translate("MainWindow", "mₙ"))
        self.pushButton_Rinf.setText(_translate("MainWindow", "R∞"))
        self.pushButton_NA.setText(_translate("MainWindow", "Nₐ"))
        self.pushButton_cos.setText(_translate("MainWindow", "cos"))
        self.pushButton_sin.setText(_translate("MainWindow", "sin"))
        self.pushButton_tan.setText(_translate("MainWindow", "tan"))
        self.pushButton_pow.setText(_translate("MainWindow", "pow"))
        self.pushButton_log.setText(_translate("MainWindow", "log"))
        self.pushButton_ln.setText(_translate("MainWindow", "ln"))
        self.pushButton_pow2.setText(_translate("MainWindow", "square"))
        self.pushButton_sqrt.setText(_translate("MainWindow", "sqrt"))
        self.pushButton_pi.setText(_translate("MainWindow", "𝛑"))
        self.pushButton_e.setText(_translate("MainWindow", "e"))
        self.pushButton_inv.setText(_translate("MainWindow", "1/x"))
        self.pushButton_factorial.setText(_translate("MainWindow", "!"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.b_del.setText(_translate("MainWindow", "DEL"))
        self.b_po.setText(_translate("MainWindow", "("))
        self.b_pf.setText(_translate("MainWindow", ")"))
        self.b_moins.setText(_translate("MainWindow", "-"))
        self.b_7.setText(_translate("MainWindow", "7"))
        self.b_8.setText(_translate("MainWindow", "8"))
        self.b_9.setText(_translate("MainWindow", "9"))
        self.b_plus.setText(_translate("MainWindow", "+"))
        self.b_4.setText(_translate("MainWindow", "4"))
        self.b_5.setText(_translate("MainWindow", "5"))
        self.b_6.setText(_translate("MainWindow", "6"))
        self.b_divise.setText(_translate("MainWindow", "÷"))
        self.b_1.setText(_translate("MainWindow", "1"))
        self.b_2.setText(_translate("MainWindow", "2"))
        self.b_3.setText(_translate("MainWindow", "3"))
        self.b_mult.setText(_translate("MainWindow", "×"))
        self.b_0.setText(_translate("MainWindow", "0"))
        self.b_point.setText(_translate("MainWindow", "."))
        self.pushButton_pm.setText(_translate("MainWindow", "+/-"))
        self.pushButton_E.setText(_translate("MainWindow", "1eˣ"))
